name: 生产-cloudladder-fe

on:
  workflow_dispatch:
env:
  NODE_VERSION: '16'
  PNPM_VERSION: '8.14.1'
  DOCKER_IMAGE: ${{ variables.DOCKER_WORKSPACE }}/cloudladder-fe
  REPOSITORY: 'lowcode-yunti/cloudladder-fe'
  BRANCH_PROD: ${{ variables.BRANCH_PROD }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  fetch-code:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.get-sha.outputs.sha }}
      date: ${{ steps.current-date.outputs.date }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.BRANCH_PROD }}
          token: ${{ secrets.CLOUD_LADDER_DISPATCH }}

      - name: Get the latest commit SHA of the repository
        id: get-sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Get current date
        id: current-date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

  build-and-push-image:
    needs: fetch-code
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.DOCKER_IMAGE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          build-args: REACT_APP_COMMIT_ID=${{ needs.fetch-code.outputs.sha }}
          push: true
          file: ./Dockerfile
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.BRANCH_PROD }}, ${{ env.DOCKER_IMAGE }}:${{ env.BRANCH_PROD }}-${{ needs.fetch-code.outputs.date }}, ${{ env.DOCKER_IMAGE }}:${{ needs.fetch-code.outputs.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
