name: PROD-cloudladder-fe

on:
  workflow_dispatch:
env:
  DOCKER_IMAGE: ${{ vars.DOCKER_WORKSPACE }}cloudladder-fe
  REPOSITORY: 'lowcode-yunti/cloudladder-fe'
  BRANCH_PROD: ${{ vars.BRANCH_PROD }}
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  ALI_OSS_ENDPOINT: cloudladder-fe.oss-cn-beijing.aliyuncs.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.BRANCH_PROD }}
          token: ${{ secrets.CLOUD_LADDER_DISPATCH }}
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Get the latest commit SHA of the repository
        id: get-sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Get current date
        id: current-date
        run: echo "::set-output name=date::$(TZ=Asia/Shanghai date +'%Y-%m-%d-%H-%M-%S')"


      - name: Build
        run: PUBLIC_URL=https://${{env.ALI_OSS_ENDPOINT}}/${{ steps.current-date.outputs.date }} yarn build
#      - name: Set up Docker Buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install OSSUtil
        run: |
          curl -O http://gosspublic.alicdn.com/ossutil/1.7.0/ossutil64
          chmod 755 ossutil64
          sudo mv ossutil64 /usr/local/bin/ossutil

      - name: Upload to OSS
        env:
          ALIYUN_OSS_ENDPOINT: ${{ env.ALI_OSS_ENDPOINT }}
          ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALI_ACCESS_KEY_ID }}
          ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALI_ACCESS_KEY_SECRET }}
          OSS_BUCKET: "cloudladder-fe"
        run: |
          ossutil config -e $ALIYUN_OSS_ENDPOINT -i $ALIYUN_ACCESS_KEY_ID -k $ALIYUN_ACCESS_KEY_SECRET -L CH
          ossutil ls oss://$OSS_BUCKET
          ossutil cp -r ./packages/lowcoder/build oss://$OSS_BUCKET/${{ steps.current-date.outputs.date }}/ # 修改为你要上传的目录

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: REACT_APP_COMMIT_ID=${{ steps.get-sha.outputs.sha }}
          push: true
          file: ./Dockerfile
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.BRANCH_PROD }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.BRANCH_PROD }}-${{ steps.current-date.outputs.date }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ steps.get-sha.outputs.sha }}
          labels: ${{ steps.meta.outputs.labels }}
#          platforms: linux/amd64,linux/arm64
