name: DEV_build-node-service

on:
  workflow_dispatch:
env:
  DOCKER_IMAGE: ${{ vars.DOCKER_WORKSPACE }}node-service
  REPOSITORY: 'huachengrx/node-service'
  BRANCH_PROD: dev
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY_HEYUAN }}
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  RANCHER_API_ENDPOINT: ${{ secrets.RANCHER_API_ENDPOINT }}
  RANCHER_PROJECT: c-m-qjl5cqb6:p-h97w4
  RANCHER_DEPLOYMENT_NAME: develop:node-service
  RANCHER_DEPLOYMENT_NAME_WORKER: develop:node-worker

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: post message
        uses: foxundermoon/feishu-action@v2
        with:
          url: https://open.feishu.cn/open-apis/bot/v2/hook/19800291-b192-440e-b9e8-890450babc6f
          msg_type: post
          content: |
            post:
              zh_cn:
                title: 开始发版-开发环境 node-service
                content:
                - - tag: text
                    un_escape: true
                    text: '开始发版-开发环境 node-service'
                  - tag: a
                    text: 查看发版详情
                    href: https://github.com/huachengrx/actions/actions/workflows/DEV_node-service.yml
                  - tag: a
                    text: 查看rancher-deployment
                    href: https://rancher-prod.22ies.com/dashboard/c/c-m-qjl5cqb6/explorer/apps.deployment/develop/node-service
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.BRANCH_PROD }}
          token: ${{ secrets.ACTION_TOKEN }}
          node-version: 20

      - name: Get the latest commit SHA of the repository
        id: get-sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Get current date
        id: current-date
        run: echo "::set-output name=date::$(TZ=Asia/Shanghai date +'%Y-%m-%d-%H-%M-%S')"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.BRANCH_PROD }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.BRANCH_PROD }}-${{ steps.current-date.outputs.date }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ steps.get-sha.outputs.sha }}
          labels: ${{ steps.meta.outputs.labels }}
  #          platforms: linux/amd64,linux/arm64

  dispatch-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Service
        run: |
          curl -X POST \
            -u "${{ secrets.RANCHER_USER_PASS }}" \
            "${{ env.RANCHER_API_ENDPOINT }}/v3/project/${{ env.RANCHER_PROJECT }}/workloads/deployment:${{ env.RANCHER_DEPLOYMENT_NAME }}?action=redeploy" &
      - name: Deploy Worker
        run: |
          curl -X POST \
            -u "${{ secrets.RANCHER_USER_PASS }}" \
            "${{ env.RANCHER_API_ENDPOINT }}/v3/project/${{ env.RANCHER_PROJECT }}/workloads/deployment:${{ env.RANCHER_DEPLOYMENT_NAME_WORKER }}?action=redeploy"
      - name: post message
        uses: foxundermoon/feishu-action@v2
        with:
          url: https://open.feishu.cn/open-apis/bot/v2/hook/19800291-b192-440e-b9e8-890450babc6f
          msg_type: post
          content: |
            post:
              zh_cn:
                title: 发版完成-开发环境 node-service
                content:
                - - tag: text
                    un_escape: true
                    text: '发版完成-开发环境 node-service'
                  - tag: a
                    text: 查看发版详情
                    href: https://github.com/huachengrx/actions/actions/workflows/DEV_node-service.yml
                  - tag: a
                    text: 查看rancher-deployment
                    href: https://rancher-prod.22ies.com/dashboard/c/c-m-qjl5cqb6/explorer/apps.deployment/develop/node-service