name: download civitai

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: 'Enter the download URL'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: download civitai
        run: |
          wget -L --content-disposition --progress=bar:force -q --show-progress '${{ github.event.inputs.download_url }}'

      - name: Upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./*
