name: download and transfer civitai

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: 'Enter the download URL'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Mock download
        run: |
          echo "This is a test file for SSH transfer." > test_file_for_ssh.txt
          echo "Mocked file: test_file_for_ssh.txt created."
          echo "::set-output name=filename::test_file_for_ssh.txt"

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: Setup SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.A100_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan ${{ secrets.A100_HOST }} >> ~/.ssh/known_hosts

      - name: Copy file to remote server
        run: |
          scp test_file_for_ssh.txt root@${{ secrets.A100_HOST }}:/data/ai/_temp_civitai_models
        env:
          filename: ${{ steps.download.outputs.filename }}
