name: download civitai

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: download civitai
        run: |
          wget -L --content-disposition -q --show-progress https://civitai.com/api/download/models/455150

      - name: Upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./*
