name: Google Colab Docker Pull and Push

on:
  workflow_dispatch:
env:
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Pull image
        run: docker pull us-docker.pkg.dev/colab-images/public/runtime

      - name: Tag image
        run: docker tag us-docker.pkg.dev/colab-images/public/runtime registry.cn-wulanchabu.aliyuncs.com/cloudladder_shangyun/google-colab

      - name: Push image
        run: docker push ${{ env.DOCKER_REGISTRY }}/${{ vars.DOCKER_WORKSPACE }}google-colab
