name: Google Colab Docker Pull and Push

on:
  push:
    branches:
      - main  # 根据你的需求更改触发事件的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.cn-wulanchabu.aliyuncs.com

      - name: Pull image
        run: docker pull us-docker.pkg.dev/colab-images/public/runtime

      - name: Tag image
        run: docker tag us-docker.pkg.dev/colab-images/public/runtime registry.cn-wulanchabu.aliyuncs.com/cloudladder_shangyun/google-colab

      - name: Push image
        run: docker push registry.cn-wulanchabu.aliyuncs.com/cloudladder_shangyun/google-colab
