name: TEST_miniapp_preview
on:
  workflow_dispatch:
env:
  BRANCH_PROD: test
  REPOSITORY: 'huachengrx/miniapp'
  CHAT_IDS: 'oc_107f404e7d4920100c6cf70246215ca3'
  FEISHU_APP_GITHUB_ID: 'cli_a6966acc9169100b'
  ENV: test
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.BRANCH_PROD }}
          token: ${{ secrets.ACTION_TOKEN }}
          node-version: 22

      - name: Get the latest commit SHA of the repository
        id: get-sha
        run: echo "sha=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

      - name: Get current date
        id: current-date
        run: echo "date=$(TZ=Asia/Shanghai date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Get last few commits
        id: last-commits
        run: |
          commits=$(git log -n 3 --pretty=format:"%h - %s" | tr '\n' ' ' | cut -c 1-100)
          echo "commits=${commits}" >> $GITHUB_OUTPUT

      - name: Write private key to file
        run: |
          echo "${{ secrets.WAPP_PRIVATE_KEY }}" > private.key
          echo "PRIVATE_KEY_PATH=$(pwd)/private.key" >> $GITHUB_ENV

      - name: Build and Upload and Preview MiniProgram
        run: |
          npm i
          npm run build:weapp
          DESC_ESCAPED=$(echo '${{steps.last-commits.outputs.commits}}' | sed "s/'/\\\\'/g")
          CI=true \
          ENV=${{env.ENV}} \
          DESC="$DESC_ESCAPED" \
          CHAT_IDS=${{env.CHAT_IDS}} \
          FEISHU_APP_GITHUB_ID=${{env.FEISHU_APP_GITHUB_ID}} \
          FEISHU_APP_GITHUB_SECRET=${{secrets.FEISHU_APP_GITHUB_SECRET}} \
          PRIVATE_KEY_PATH=${{env.PRIVATE_KEY_PATH}} \
          npm run upload
