name: xiwang_DEV_build-admin-backend

on:
  workflow_dispatch:
env:
  DOCKER_IMAGE: ${{ vars.DOCKER_WORKSPACE }}admin-backend
  REPOSITORY: 'lowcode-yunti/admin-backend'
  BRANCH_PROD: xiwang/dev
  BRANCH_TAG: xiwang_dev
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY_SHANGHAI }}
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  FEISHU_ENV_NAME: '开发环境'
  FEISHU_PROJECT_NAME: '管理后台-后端'
  FEISHU_ACTION_URL: 'https://github.com/lowcode-yunti/actions/actions/workflows/xiwang_DEV_admin-backend-docker.yml'
  FEISHU_URL: 'https://open.feishu.cn/open-apis/bot/v2/hook/573169c4-e377-4b63-8e7f-7e410c3b8a6a'
  FEISHU_RANCHER_URL: 'https://r.dev.xurifukangngo.com/dashboard/c/local/explorer/apps.deployment/dev/admin-python-be'
  RANCHER_API_ENDPOINT: https://r.dev.xurifukangngo.com
  RANCHER_PROJECT: local:p-fb9kw
  RANCHER_DEPLOYMENT_NAME: dev:admin-python-be
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: post message
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ env.FEISHU_URL }}
          msg_type: post
          content: |
            post:
              zh_cn:
                title: 开始发版-${{ env.FEISHU_ENV_NAME }} ${{ env.FEISHU_PROJECT_NAME }}
                content:
                - - tag: text
                    un_escape: true
                    text: '开始发版-${{ env.FEISHU_ENV_NAME }} ${{ env.FEISHU_PROJECT_NAME }}'
                  - tag: a
                    text: 查看发版详情
                    href: ${{ env.FEISHU_ACTION_URL }}
                  - tag: a
                    text: 查看rancher-deployment
                    href: ${{ env.FEISHU_RANCHER_URL}}
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPOSITORY }}
          ref: ${{ env.BRANCH_PROD }}
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Get the latest commit SHA of the repository
        id: get-sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Get current date
        id: current-date
        run: echo "::set-output name=date::$(TZ=Asia/Shanghai date +'%Y-%m-%d-%H-%M-%S')"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: REACT_APP_COMMIT_ID=${{ steps.get-sha.outputs.sha }}
          push: true
          file: ./docker/Dockerfile
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.BRANCH_TAG }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.BRANCH_TAG }}-${{ steps.current-date.outputs.date }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ steps.get-sha.outputs.sha }}
          labels: ${{ steps.meta.outputs.labels }}
  #          platforms: linux/amd64,linux/arm64

  dispatch-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dev
        run: |
          curl -X POST \
            -u "${{ secrets.QIWANG_RANCHER_USER_PASS }}" \
            "${{ env.RANCHER_API_ENDPOINT }}/v3/project/${{ env.RANCHER_PROJECT }}/workloads/deployment:${{ env.RANCHER_DEPLOYMENT_NAME }}?action=redeploy"
      - name: post message
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ env.FEISHU_URL }}
          msg_type: post
          content: |
            post:
              zh_cn:
                title: 发版完成-${{ env.FEISHU_ENV_NAME }} ${{ env.FEISHU_PROJECT_NAME }}
                content:
                - - tag: text
                    un_escape: true
                    text: '发版完成-${{ env.FEISHU_ENV_NAME }} ${{ env.FEISHU_PROJECT_NAME }}'
                  - tag: a
                    text: 查看发版详情
                    href: ${{ env.FEISHU_ACTION_URL }}
                  - tag: a
                    text: 查看rancher-deployment
                    href: ${{ env.FEISHU_RANCHER_URL}}
